server:
  port: 8080
  platform: dev
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      base-path: /promotions
spring:
  profiles:
    active: ${PROFILE:dh}
  application:
    name: color-picker-api
  #===== Authorization check ====== #
design:
  hub:
    token:
      excludePathPatterns:
    auth:
      client_id: ***REMOVED***
      client_secret: ***REMOVED***
      url: https://signon.michaels.com/mga/sps/oauth/oauth20/introspect
    promotions:
      url: https://tibcoapiintegrationpre.michaels.com:443/promorequest
#===== stag ===== #
dotNet:
  host: "https://dh-gso-dotnet-svc-stg.herokuapp.com"
  uri: "/api/v1/gso"

# ===== log===== #
logging:
  level:
    root: ${LOG_LEVEL:INFO}
  config:
    classpath: logback.xml
    path: ./log/${spring.application.name}


