server:
  port: 8080
  platform: dev
  servlet:
    context-path: /api
spring:
  application:
    name: color-picker-api
  #i18n
  messages:
    basename: i18n/messages
    encoding: UTF-8
  #==== db info ====#
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-217-53-211.compute-1.amazonaws.com:5432/ds2fo83ti1vo2?sslmode=require&sslrootcert=./certs/root.crt&sslcert=./certs/postgresql.crt&sslkey=./certs/postgresql.pk8
    username: ***REMOVED***
    password: ***REMOVED***
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 10
      idle-timeout: 60000
      maximum-pool-size: 80
      auto-commit: true
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
      ddl-auto: update
      globally_quoted_identifiers: true
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: com.michaels.designhub.config.PostgreSQL10JsonDialect
        ddl-auto: update
        globally_quoted_identifiers: true
#===== Authorization check ===== #
design:
  hub:
    token:
      excludePathPatterns:
    auth:
      client_id: ***REMOVED***
      client_secret: ***REMOVED***
      url: https://signon.michaels.com/mga/sps/oauth/oauth20/introspect
    promotions:
      url: https://tibcoapiintegrationpre.michaels.com:443/promorequest
#===== stag ===== #
dotNet:
  host: "https://dh-gso-dotnet-svc-stg.herokuapp.com"
  uri: "/api/v1/gso"

# ===== log===== # 
logging:
  level:
    root: ${LOG_LEVEL:INFO}
  config:
    classpath: logback.xml
    path: ./log/${spring.application.name}


